[general]
live_config_reload = true
import = [
  # "/home/shank/.config/alacritty/themes/everforest_light_medium.toml",
  # "/home/shank/.config/alacritty/themes/catppuccin-latte.toml",
  # "/home/shank/.config/alacritty/themes/tokyonight_day.toml",
  # "/home/shank/.config/alacritty/themes/zenbones_light.toml",
  "/home/shank/.config/alacritty/themes/gruvbox_material_hard_light.toml",
]

[font]
# size = 12.0
size = 11.0
# size = 10.5
# size = 10.0
# size = 9.0

[font.offset]
# x = 0
# x = 1
# y = 4
# y = 3
# y = 2
# y = 1
# y = 0
# y = -1
# y = -2

[font.bold]
# family = "CommitMonoThicker"
style = "Bold"
# family = "JetBrainsMono Nerd Font"
family = "JetBrainsMono"
# family = "SF Mono"
# family = "Comic Mono"
# family = "Ubuntu Mono"
# family = "Codelia"
# family = "Berkeley Mono"
# family = "NotoSansM Nerd Font Mono SemiCondensed Medium"
# family = "NotoSansM Nerd Font Mono Condensed Medium"
# family = "Noto Sans Mono"
# family = "Pragmasevka Nerd Font"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
# family = "CommitMonoThicker"
style = "Italic"
# family = "JetBrainsMono Nerd Font"
family = "JetBrainsMono"
# family = "SF Mono"
# family = "Comic Mono"
# family = "Ubuntu Mono"
# family = "Codelia"
# family = "Berkeley Mono"
# family = "NotoSansM Nerd Font Mono SemiCondensed Medium"
# family = "NotoSansM Nerd Font Mono Condensed Medium"
# family = "Noto Sans Mono"
# family = "Pragmasevka Nerd Font"

[font.normal]
# family = "CommitMonoThicker"
# style = "Normal"
# family = "JetBrainsMono Nerd Font"
family = "JetBrainsMono"
# family = "SF Mono"
# family = "Comic Mono"
# family = "Ubuntu Mono"
# family = "Codelia"
# family = "Berkeley Mono"
# family = "NotoSansM Nerd Font Mono SemiCondensed Medium"
# family = "NotoSansM Nerd Font Mono Condensed Medium"
# family = "Noto Sans Mono"
# family = "Pragmasevka Nerd Font"
# family = "PragmataPro"
# style = "Bold"
# style = "Semibold"
style = "Medium"
# style = "Retina"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50000

[window]
opacity = 1

[window.padding]
x = 2
# y = 0

[terminal]
osc52 = "CopyPaste"
